"""
Regenerates docs/grammatike-api-docs.html: a single self-contained HTML
page documenting grammatike's public API (every name in
`grammatike.__all__` -- see grammatike/__init__.py), built with pdoc
directly from that code's own docstrings and type hints.

Greek analogue of arsgrammatica's docs/build_api_docs.py.

Deliberately scoped to ONE page for the top-level package only, not a
multi-page site with one page per submodule (models.py, rendering.py,
etc.) -- pdoc still pulls each name's real signature and docstring from
wherever it's actually defined, so nothing is lost by excluding submodule
pages; it just keeps the output to the same single browsable file
regardless of how many internal modules the package grows into. The
exclude list is computed from the package's own submodules (via
pkgutil.iter_modules) rather than hardcoded, so a new internal module added
later is excluded automatically without needing an edit here.

Run from anywhere:
    python docs/build_api_docs.py

Requires pdoc (`pip install pdoc --break-system-packages`); not currently
pinned in a requirements file anywhere in this repo, so install it by hand
if it's missing.
"""

import pkgutil
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_FILE = Path(__file__).resolve().parent / "grammatike-api-docs.html"

# So `import grammatike` below works no matter what directory this
# script is invoked from.
sys.path.insert(0, str(REPO_ROOT))

try:
    import pdoc
    import pdoc.render
except ImportError:
    sys.exit(
        "pdoc is required to build the API docs but isn't installed.\n"
        "Install it with: pip install pdoc --break-system-packages"
    )

import grammatike


def _submodule_exclude_patterns():
    """One '!grammatike.<name>' pattern per actual submodule of the
    grammatike package, so pdoc renders only the top-level package page
    (see this file's own docstring for why)."""
    return [
        f"!grammatike.{info.name}"
        for info in pkgutil.iter_modules(grammatike.__path__)
    ]


def build():
    pdoc.render.configure(
        docformat="google",
        footer_text=(
            "grammatike public API -- generated by docs/build_api_docs.py "
            "from the package's own docstrings; do not edit by hand."
        ),
        search=False,
        math=False,
        mermaid=False,
    )

    with tempfile.TemporaryDirectory() as tmp:
        pdoc.pdoc(
            "grammatike",
            *_submodule_exclude_patterns(),
            output_directory=Path(tmp),
        )
        rendered = Path(tmp) / "grammatike.html"
        OUTPUT_FILE.write_bytes(rendered.read_bytes())

    print(f"Wrote {OUTPUT_FILE} ({OUTPUT_FILE.stat().st_size:,} bytes)")


if __name__ == "__main__":
    build()
